# Site settings
title: Emerald Craft
description: "A Minecraft site designed by Nolan"
url: "http://notmeirl.js.org"
author:
  name: "Nolan"
  email: "animenolan@gmail.com"
  url: "http://notmeirl.js.org"

# Build settings
baseurl: /emerald/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
